# Generated by Django 5.2.14 on 2026-08-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donatablecategory',
            name='image',
            field=models.CharField(blank=True, default='', help_text='Path under static/, e.g. categorized_product/donate/wheelchair.jpg', max_length=200),
        ),
    ]
