"""
Django settings for sajhya_project project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import environ
import os

BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()

# Load .env only if present (local development)
if os.path.exists(BASE_DIR / '.env'):
    environ.Env.read_env(BASE_DIR / '.env')


SECRET_KEY = env('SECRET_KEY')
DEBUG = env.bool('DEBUG', default=False)
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS')
DATABASES = {
    'default': {
        **env.db(),
        'OPTIONS': {'charset': 'utf8mb4'},
    }
}
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
    'corsheaders',
    'account_app',
    'personal_account',
    'clinic_account',
    'enterprise_account',
    'exercise_app',
    'import_export',
    'detail_app',
    'video_app',
    'patient_app',
    'prescription_app',
    'upload_app',
    'referral_app',
    'marketplace_app',
    'find_physio_app',
    'summit_app',
    'visit_notes_app',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # ✅ must be here
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sajhya_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sajhya_project.wsgi.application'






AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'account_app.User'
# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
USE_I18N = True
TIME_ZONE = 'Asia/Kathmandu'
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_ROOT = BASE_DIR / 'staticfiles'
STATIC_URL = 'static/'


# This tells Django where to find additional static directories (outside apps)
STATICFILES_DIRS = [
    BASE_DIR / "static",   # <-- This must point to your static folder
]

# WhiteNoise serves everything under STATIC_ROOT directly from the Django/WSGI
# process itself (via WhiteNoiseMiddleware above). This is needed because the
# Passenger/LiteSpeed hosting here only serves a URL straight from disk when a
# literal file exists at that exact path relative to the app root -- it has no
# separate "/static/ -> staticfiles/" alias configured, so anything only
# present after `collectstatic` (Django admin's own CSS/JS, django-import-export's,
# etc.) was 404ing. WhiteNoise removes the need for that web-server-level mapping.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Media files (User uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'   # Creates 'media' folder in your project root

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Increase global Django limits (prevents "too large" errors)
DATA_UPLOAD_MAX_MEMORY_SIZE = 200 * 1024 * 1024  # 200 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 200 * 1024 * 1024  # 200 MB

# Optional: Restrict file uploads to APK only (enforced at view level too)
ALLOWED_APK_MIME_TYPES = ['application/vnd.android.package-archive']



# CORS - allow Flutter app requests
CORS_ALLOWED_ORIGINS = [
    "https://sajhya.com",
]
CORS_ALLOW_CREDENTIALS = True

# Session cookie - required for mobile cross-origin cookie persistence
SESSION_COOKIE_SAMESITE = 'None'
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_AGE = 60 * 60 * 24 * 30  # 30 days
SESSION_SAVE_EVERY_REQUEST = True

# CSRF
CSRF_TRUSTED_ORIGINS = [
    "https://sajhya.com",
]
CSRF_COOKIE_SAMESITE = 'None'
CSRF_COOKIE_SECURE = True

# Web Push (patient notifications, e.g. clinic queue "Call for Session")
VAPID_PUBLIC_KEY = env('VAPID_PUBLIC_KEY')
VAPID_PRIVATE_KEY = env('VAPID_PRIVATE_KEY')
VAPID_CLAIM_EMAIL = env('VAPID_CLAIM_EMAIL')