# Generated by Django 5.2.14 on 2026-07-05 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise_name', models.CharField(max_length=255)),
                ('enterprise_code', models.CharField(editable=False, max_length=14, unique=True)),
                ('pan_number', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enterprises', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EnterpriseStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_enterprise', to='enterprise_account.enterprise')),
                ('physio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_enterprise_physio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('enterprise', 'physio')},
            },
        ),
    ]
