# Generated by Django 5.2.14 on 2026-07-03 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_account', '0005_alter_clinicphysio_clinic_alter_clinicphysio_physio'),
        ('enterprise_account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentClinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('attached_at', models.DateTimeField(auto_now_add=True)),
                ('attached_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinic_attachments', to=settings.AUTH_USER_MODEL)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_departments', to='clinic_account.clinic')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attached_clinics', to='enterprise_account.department')),
            ],
            options={
                'unique_together': {('department', 'clinic')},
            },
        ),
    ]
