# Generated by Django 5.2.14 on 2026-07-05 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_name', models.CharField(max_length=100)),
                ('ward_type', models.CharField(choices=[('icu', 'ICU'), ('hdu', 'HDU'), ('surgical', 'Surgical'), ('medical', 'Medical'), ('ccu', 'CCU'), ('general', 'General'), ('emergency', 'Emergency'), ('maternity', 'Maternity')], default='general', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wards_created', to=settings.AUTH_USER_MODEL)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='enterprise_account.enterprise')),
            ],
            options={
                'unique_together': {('enterprise', 'ward_name')},
            },
        ),
    ]
