# Generated by Django 5.2.14 on 2026-07-05 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_account', '0002_ward'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='access_token',
            field=models.CharField(default='', editable=False, max_length=24, unique=True),
        ),
        migrations.AddField(
            model_name='ward',
            name='pin',
            field=models.CharField(blank=True, help_text='Plaintext copy shown to the enterprise owner. Login still checks pin_hash.', max_length=10),
        ),
        migrations.AddField(
            model_name='ward',
            name='pin_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.CreateModel(
            name='PhysioRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('bed_number', models.CharField(blank=True, max_length=20)),
                ('reason', models.TextField()),
                ('urgency', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent')], default='routine', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('handled', 'Handled')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physio_requests_handled', to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physio_requests', to='enterprise_account.ward')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
