# Generated by Django 5.2.14 on 2026-07-05 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_account', '0003_ward_access_token_ward_pin_ward_pin_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ward',
            name='access_token',
            field=models.CharField(editable=False, max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='ward',
            name='pin_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
