# Generated by Django 5.2.14 on 2026-07-05 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_account', '0004_alter_ward_access_token_alter_ward_pin_hash'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ward',
            unique_together={('enterprise', 'ward_type')},
        ),
        migrations.RemoveField(
            model_name='ward',
            name='ward_name',
        ),
    ]
