# Generated by Django 5.2.14 on 2026-07-07 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_account', '0005_alter_ward_unique_together_remove_ward_ward_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='physiorequest',
            old_name='handled_at',
            new_name='status_updated_at',
        ),
        migrations.RemoveField(
            model_name='physiorequest',
            name='handled_by',
        ),
        migrations.AddField(
            model_name='physiorequest',
            name='physio_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='physiorequest',
            name='status_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physio_requests_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='physiorequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('seen', 'Seen'), ('noted', 'Noted'), ('handled', 'Handled')], default='pending', max_length=10),
        ),
    ]
