# Generated by Django 5.2.14 on 2026-07-07 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_account', '0006_rename_handled_at_physiorequest_status_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physiorequest',
            name='reason',
            field=models.CharField(choices=[('chest', 'Chest'), ('chest_limb', 'Chest + Limb'), ('limb', 'Limb'), ('ambulation', 'Ambulation'), ('postural_drainage', 'Postural Drainage'), ('other', 'Other')], default='chest', max_length=20),
        ),
    ]
