# Generated by Django 5.2.14 on 2026-08-18 02:27

import django.db.models.deletion
import personal_account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0021_exercisemain_youtube_url'),
        ('patient_app', '0001_initial'),
        ('personal_account', '0012_addpatient_is_deleted_addpatient_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_id_in_library', models.IntegerField(db_index=True)),
                ('exercise_name', models.CharField(blank=True, default='', max_length=200)),
                ('clicked_at', models.DateTimeField(default=personal_account.models.get_nepal_time)),
                ('prescription_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_click_events', to='exercise_app.prescriptionexercise')),
            ],
            options={
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.CreateModel(
            name='AppOpenEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_on', models.DateField(help_text='Calendar date (Asia/Kathmandu) the app was opened')),
                ('first_opened_at', models.DateTimeField(default=personal_account.models.get_nepal_time)),
                ('ping_count', models.PositiveIntegerField(default=1, help_text='How many times the ping fired that day -- informational only, not a distinct metric')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_open_events', to='personal_account.addpatient')),
            ],
            options={
                'ordering': ['-opened_on'],
                'unique_together': {('patient', 'opened_on')},
            },
        ),
    ]
