# Generated by Django 5.2.14 on 2026-07-02 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_app', '0004_commission_commissionrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisProductMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(blank=True, max_length=150)),
                ('products', models.ManyToManyField(blank=True, related_name='diagnosis_maps', to='marketplace_app.product')),
            ],
            options={
                'verbose_name': 'Diagnosis → Product Map',
                'verbose_name_plural': 'Diagnosis → Product Maps',
                'ordering': ['keyword'],
            },
        ),
    ]
