# Generated by Django 5.2.14 on 2026-07-02 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_app', '0006_patientproductrecommendation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosisproductmap',
            options={'ordering': ['keyword'], 'verbose_name': 'Diagnosis-Product Map', 'verbose_name_plural': 'Diagnosis-Product Maps'},
        ),
    ]
