# Generated by Django 5.2.14 on 2026-08-19 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_app', '0012_diaper_fixderma_kleida_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order, after the main product photo')),
                ('image', models.CharField(help_text='Same path convention as Product.image', max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='marketplace_app.product')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
