# Generated by Django 5.2.14 on 2026-08-24 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_app', '0013_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, help_text='Optional free-text grouping, e.g. "Pain Relief" -- shown on the product page, not filterable yet.', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='per piece', max_length=50)),
                ('image', models.CharField(blank=True, default='', max_length=200)),
                ('in_stock', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('requires_prescription', models.BooleanField(default=False, help_text='Shows an Rx-required badge on the storefront.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_featured', 'name'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('marketplace', 'Marketplace'), ('pharmacy', 'Pharmacy')], default='marketplace', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pharmacy_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace_app.pharmacyproduct'),
        ),
    ]
