# Generated by Django 5.2.14 on 2026-08-24 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_app', '0002_labtestpanel'),
        ('marketplace_app', '0015_migrate_pharmacy_products_to_own_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='lab_panel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab_app.labtestpanel'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='lab_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab_app.labtest'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('marketplace', 'Marketplace'), ('pharmacy', 'Pharmacy'), ('lab_test', 'Lab Test')], default='marketplace', max_length=20),
        ),
    ]
