# Generated by Django 5.2.14 on 2026-09-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_app', '0016_orderitem_lab_panel_orderitem_lab_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, default='', help_text='e.g. "Zuvara", "UM Orthotics" -- shown under the product name so visually similar items from different catalogs (same photo style, different price) aren\'t confused for each other. Blank is fine for products with no real brand.', max_length=100),
        ),
    ]
