# Generated by Django 5.2.14 on 2026-09-28 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_app', '0017_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyproduct',
            name='image_upload',
            field=models.ImageField(blank=True, help_text='Upload a photo directly. Takes priority over the static path above when both are set.', null=True, upload_to='pharmacy_uploads/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_upload',
            field=models.ImageField(blank=True, help_text='Upload a photo directly. Takes priority over the static path above when both are set.', null=True, upload_to='marketplace_uploads/'),
        ),
        migrations.AlterField(
            model_name='pharmacyproduct',
            name='image',
            field=models.CharField(blank=True, default='', help_text='Legacy static path under static/, e.g. categorized_product/pharmacy/gabapin.jpg. Prefer uploading a photo below for new products -- this is only still here for products photographed this way before direct upload existed.', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, default='', help_text='Legacy static path under static/, e.g. categorized_product/9/9 (023).png. Prefer uploading a photo below for new products -- this is only still here for products photographed this way before direct upload existed.', max_length=200),
        ),
    ]
