# Generated by Django 5.2.14 on 2026-08-23 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(default='Kathmandu, Nepal', max_length=150)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('internship', 'Internship')], default='full_time', max_length=20)),
                ('description', models.TextField(help_text='What the role involves.')),
                ('requirements', models.TextField(blank=True, help_text='One requirement per line -- rendered as a bullet list.')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to close/hide this vacancy without deleting it (past applications stay intact).')),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('closing_date', models.DateField(blank=True, help_text='Optional -- shown as an "Apply by" date if set.', null=True)),
            ],
            options={
                'verbose_name_plural': 'Vacancies',
                'ordering': ['-posted_at'],
            },
        ),
        migrations.CreateModel(
            name='VacancyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp_number', models.CharField(blank=True, help_text='Include country code, e.g. +9779812345678 -- used for the WhatsApp follow-up link in admin, not sent automatically.', max_length=20)),
                ('resume', models.FileField(blank=True, null=True, upload_to='careers/resumes/%Y/%m/')),
                ('cover_note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='new', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal only -- never shown to the applicant.')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='careers_app.vacancy')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
    ]
