# Generated by Django 5.2.14 on 2026-08-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='organization',
            field=models.CharField(default='Sajhya', help_text="Who's actually hiring -- 'Sajhya' for in-house roles, or the partner clinic/institute's name (e.g. 'Pinnacle Rehab Clinic') if posted on their behalf.", max_length=150),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='department',
            field=models.CharField(blank=True, help_text="Team/function within that organization, e.g. 'Physiotherapy', 'Engineering'.", max_length=100),
        ),
    ]
