# Generated by Django 5.2.14 on 2026-08-25 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_app', '0002_labtestpanel'),
        ('personal_account', '0013_diagnosiscode_addpatient_diagnosis_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestrequest',
            name='collection_address',
            field=models.TextField(blank=True, help_text='Where the sample should be collected from'),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='labtestrequestitem',
            name='lab_panel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab_app.labtestpanel'),
        ),
        migrations.AlterField(
            model_name='labtestrequest',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_requests', to='personal_account.addpatient'),
        ),
    ]
