# Generated by Django 5.2.14 on 2026-07-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0014_exercisefeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='condition_label',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
