# Generated by Django 5.2.14 on 2026-07-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0015_prescription_condition_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionexercise',
            name='schedule_day',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='prescriptionexercise',
            name='schedule_evening',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='prescriptionexercise',
            name='schedule_morning',
            field=models.BooleanField(default=True),
        ),
    ]
