# Generated by Django 5.2.14 on 2026-07-08 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0016_prescriptionexercise_schedule_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionexercise',
            name='schedule_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='prescriptionexercise',
            name='schedule_evening',
            field=models.BooleanField(default=False),
        ),
    ]
