# Generated by Django 5.2.14 on 2026-07-11 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0017_alter_prescriptionexercise_schedule_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseStepImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(help_text='1-based step number')),
                ('image_url', models.URLField()),
                ('label', models.CharField(blank=True, help_text='e.g. "Starting position"', max_length=100, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_images', to='exercise_app.exercisemain')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('exercise', 'order')},
            },
        ),
    ]
