# Generated by Django 5.2.14 on 2026-07-17 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0018_exercisestepimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisemain',
            name='exercise_description_nepali',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
