# Generated by Django 5.2.14 on 2026-07-17 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0019_exercisemain_exercise_description_nepali'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisemain',
            name='exercise_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='exercisemain',
            name='exercise_description_nepali',
            field=models.TextField(blank=True, default=''),
        ),
    ]
