# Generated by Django 5.2.14 on 2026-07-19 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0020_alter_exercisemain_exercise_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisemain',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Link to a YouTube video demonstrating this exercise', null=True),
        ),
    ]
