# Generated by Django 5.2.14 on 2026-08-18 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0021_exercisemain_youtube_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
