# Generated by Django 5.2.14 on 2026-09-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0022_prescription_end_date_prescription_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisemain',
            name='hosted_video_url',
            field=models.URLField(blank=True, help_text='Direct video file URL (e.g. Supabase Storage public URL) played embedded in-app; takes priority over youtube_url when set', null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('superseded', 'Superseded')], default='active', max_length=20),
        ),
    ]
