# Generated by Django 5.2.14 on 2026-07-03 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('label', models.CharField(blank=True, max_length=50)),
                ('pin_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='SessionSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(choices=[('session1', 'Session 1: Minimum Standards'), ('session2', 'Session 2: Service Pricing'), ('session3', 'Session 3: Professional Compensation')], max_length=20)),
                ('facilitator_name', models.CharField(blank=True, max_length=100)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('current_step', models.PositiveSmallIntegerField(default=1)),
                ('is_complete', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='summit_app.table')),
            ],
            options={
                'ordering': ['table__number', 'session_key'],
                'unique_together': {('table', 'session_key')},
            },
        ),
    ]
