# Generated by Django 5.2.14 on 2026-07-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='is_claimed',
            field=models.BooleanField(default=False),
        ),
    ]
