# Generated by Django 5.2.14 on 2026-07-04 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit_app', '0002_table_claimed_at_table_is_claimed'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='pin',
            field=models.CharField(blank=True, help_text='Plaintext copy shown to staff on the admin dashboard. Login still checks pin_hash.', max_length=10),
        ),
    ]
