# Generated by Django 5.2.14 on 2026-07-05 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_account', '0001_initial'),
        ('personal_account', '0005_addpatient_qr_code_addpatient_qr_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='addpatient',
            name='origin_enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enterprise_assigned', to='enterprise_account.enterprise'),
        ),
    ]
