# Generated by Django 5.2.14 on 2026-08-03 03:42

import django.db.models.deletion
import personal_account.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_account', '0006_queueentry'),
        ('enterprise_account', '0007_alter_physiorequest_reason'),
        ('personal_account', '0007_addpatient_activation_expires_at_activationcard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpatient',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='physio_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PatientPhysioPairing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('self_registered_qr', 'Self-registered via QR'), ('physio_created', 'Physio-created'), ('referral', 'Referral')], max_length=20)),
                ('paired_at', models.DateTimeField(default=personal_account.models.get_nepal_time)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_pairings', to='clinic_account.clinic')),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_pairings', to='enterprise_account.enterprise')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairings', to='personal_account.addpatient')),
                ('physio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_pairings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('patient', 'physio')},
            },
        ),
    ]
