# Generated by Django 5.2.14 on 2026-08-03 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0009_backfill_patient_physio_pairing'),
    ]

    operations = [
        migrations.AddField(
            model_name='addpatient',
            name='password',
            field=models.CharField(blank=True, help_text='Hashed, never stored in plain text', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='addpatient',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
