# Generated by Django 5.2.14 on 2026-08-03 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0010_addpatient_password_addpatient_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addpatient',
            name='username',
        ),
    ]
