# Generated by Django 5.2.14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0011_remove_addpatient_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='addpatient',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='addpatient',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
