# Generated by Django 5.2.14 on 2026-08-18 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0012_addpatient_is_deleted_addpatient_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='ICD-10 code, e.g. M54.5', max_length=10, unique=True)),
                ('label', models.CharField(help_text='e.g. "Low back pain"', max_length=200)),
                ('chapter', models.CharField(blank=True, help_text='e.g. "Musculoskeletal", "Neurological", "Injury", "Aftercare"', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='addpatient',
            name='diagnosis_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='personal_account.diagnosiscode'),
        ),
    ]
