# Generated by Django 5.2.14 on 2026-10-01 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0013_diagnosiscode_addpatient_diagnosis_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientMedicalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_medications', models.TextField(blank=True, default='', help_text='e.g. "Metformin 500mg twice daily, Atorvastatin 10mg at night"')),
                ('allergies', models.TextField(blank=True, default='', help_text='Drug, food, or other allergies and reactions')),
                ('routine_tests', models.TextField(blank=True, default='', help_text='Tests done periodically, e.g. "HbA1c every 3 months, Lipid profile every 6 months"')),
                ('medical_history', models.TextField(blank=True, default='', help_text='Past surgeries, chronic conditions, hospitalizations, family history')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_profile', to='personal_account.addpatient')),
            ],
        ),
    ]
