# Generated by Django 5.2.14 on 2026-10-04 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0014_patientmedicalprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='addpatient',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
