# Generated by Django 5.2.14 on 2026-10-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0015_addpatient_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmedicalprofile',
            name='physiotherapy_history',
            field=models.TextField(blank=True, default='', help_text='Past physiotherapy treatment, injuries, or surgeries relevant to movement/rehab -- e.g. "ACL reconstruction 2022, 6 months of physio afterward"'),
        ),
    ]
