# Generated by Django 5.2.14 on 2026-10-04 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_app', '0003_labtestrequest_collection_address_and_more'),
        ('marketplace_app', '0018_pharmacyproduct_image_upload_product_image_upload_and_more'),
        ('personal_account', '0016_patientmedicalprofile_physiotherapy_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientmedicalprofile',
            name='current_medications',
        ),
        migrations.RemoveField(
            model_name='patientmedicalprofile',
            name='physiotherapy_history',
        ),
        migrations.RemoveField(
            model_name='patientmedicalprofile',
            name='routine_tests',
        ),
        migrations.AddField(
            model_name='patientmedicalprofile',
            name='nursing_mobility_assistance',
            field=models.TextField(blank=True, default='', help_text='Help needed with transfers, walking, toileting, etc.'),
        ),
        migrations.AddField(
            model_name='patientmedicalprofile',
            name='nursing_vitals',
            field=models.TextField(blank=True, default='', help_text='Vitals tracking, e.g. "BP 120/80, Pulse 72, Temp 98.6F -- checked daily"'),
        ),
        migrations.AddField(
            model_name='patientmedicalprofile',
            name='nursing_wound_catheter_care',
            field=models.TextField(blank=True, default='', help_text='Wound dressing, catheter, or ostomy care needs'),
        ),
        migrations.CreateModel(
            name='PatientBloodTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.CharField(blank=True, default='', help_text='e.g. "every 3 months", or a past result', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lab_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab_app.labtest')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_test_entries', to='personal_account.addpatient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_day', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening'), ('night', 'Night')], max_length=10)),
                ('custom_name', models.CharField(blank=True, default='', max_length=200)),
                ('instructions', models.CharField(blank=True, default='', help_text='e.g. "500mg, after food"', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='personal_account.addpatient')),
                ('pharmacy_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace_app.pharmacyproduct')),
            ],
            options={
                'ordering': ['time_of_day', 'created_at'],
            },
        ),
    ]
