# Generated by Django 5.2.14 on 2026-10-04 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_app', '0018_pharmacyproduct_image_upload_product_image_upload_and_more'),
        ('personal_account', '0017_remove_patientmedicalprofile_current_medications_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aids', to='personal_account.addpatient')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace_app.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
