# Generated by Django 5.2.14 on 2026-10-04 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0023_exercisemain_hosted_video_url_and_more'),
        ('personal_account', '0018_patientaid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise_app.exercisemain')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_exercises', to='personal_account.addpatient')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('patient', 'exercise')},
            },
        ),
    ]
