# Generated by Django 5.2.14 on 2026-10-05 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_app', '0002_alter_regionalassessment_region_and_more'),
        ('personal_account', '0019_patientexercise'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAssessmentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_entries', to='personal_account.addpatient')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment_app.specialtestreference')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('patient', 'reference')},
            },
        ),
    ]
