# Generated by Django 5.2.14 on 2026-10-05 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0020_patientassessmententry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientphysiopairing',
            name='source',
            field=models.CharField(choices=[('self_registered_qr', 'Self-registered via QR'), ('physio_created', 'Physio-created'), ('referral', 'Referral'), ('physio_claimed', 'Physio Added Existing Patient')], max_length=20),
        ),
    ]
