# Generated by Django 5.2.14 on 2026-10-06 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_app', '0018_pharmacyproduct_image_upload_product_image_upload_and_more'),
        ('personal_account', '0024_patientconsultation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(blank=True, default='', max_length=200)),
                ('dosage', models.CharField(blank=True, default='', help_text='e.g. "500mg, 1 tablet"', max_length=100)),
                ('time_of_day', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening'), ('night', 'Night')], max_length=10)),
                ('start_date', models.DateField()),
                ('duration_days', models.PositiveIntegerField(blank=True, help_text='Leave blank for ongoing / as-needed', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('discontinued', 'Discontinued')], default='active', max_length=15)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rx_list', to='personal_account.addpatient')),
                ('pharmacy_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace_app.pharmacyproduct')),
            ],
            options={
                'ordering': ['-start_date', '-created_at'],
            },
        ),
    ]
