# Generated by Django 5.2.14 on 2026-07-05 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal_account', '0006_addpatient_origin_enterprise'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chief_complaint_today', models.TextField(blank=True)),
                ('pain_score', models.PositiveSmallIntegerField(blank=True, help_text='0-10', null=True)),
                ('pain_at_rest', models.BooleanField(default=False)),
                ('pain_with_activity', models.BooleanField(default=False)),
                ('pain_worst_24hr', models.BooleanField(default=False)),
                ('pain_quality_location', models.TextField(blank=True)),
                ('hep_adherence', models.CharField(blank=True, choices=[('100', '100%'), ('75', '75%'), ('50', '50%'), ('0', '0%')], max_length=3)),
                ('hep_adherence_reason', models.CharField(blank=True, max_length=255)),
                ('changes_since_last_visit', models.CharField(blank=True, choices=[('better', 'Better'), ('worse', 'Worse'), ('same', 'Same')], max_length=10)),
                ('changes_description', models.TextField(blank=True)),
                ('current_function_adls', models.TextField(blank=True)),
                ('medication_changes', models.TextField(blank=True)),
                ('new_concerns_alerts', models.TextField(blank=True)),
                ('vitals_hr', models.CharField(blank=True, max_length=20)),
                ('vitals_bp', models.CharField(blank=True, max_length=20)),
                ('vitals_rr', models.CharField(blank=True, max_length=20)),
                ('rom_active', models.TextField(blank=True)),
                ('rom_passive', models.TextField(blank=True)),
                ('strength_mmt', models.TextField(blank=True)),
                ('palpation_swelling', models.TextField(blank=True)),
                ('special_tests', models.TextField(blank=True)),
                ('functional_test_baseline', models.TextField(blank=True)),
                ('outcome_measure', models.CharField(blank=True, max_length=255)),
                ('primary_impairment_today', models.TextField(blank=True)),
                ('contraindications_precautions', models.TextField(blank=True)),
                ('patient_goals_session', models.TextField(blank=True)),
                ('post_pain_score', models.PositiveSmallIntegerField(blank=True, help_text='0-10', null=True)),
                ('post_rom', models.TextField(blank=True)),
                ('post_strength', models.TextField(blank=True)),
                ('post_functional_test', models.TextField(blank=True)),
                ('assessment', models.TextField(blank=True, help_text='Compare post-treatment findings to the pre-treatment baseline above.')),
                ('plan', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_notes_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_notes', to='personal_account.addpatient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
