# Generated by Django 5.2.14 on 2026-07-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit_notes_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitnote',
            name='case_type',
            field=models.CharField(choices=[('ortho', 'Orthopedic'), ('neuro', 'Neurological'), ('geriatric', 'Geriatric')], default='ortho', max_length=10),
        ),
        migrations.AddField(
            model_name='visitnote',
            name='geri_appetite',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='visitnote',
            name='geri_bp_seated',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='visitnote',
            name='geri_bp_standing_post',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='visitnote',
            name='geri_bp_standing_pre',
            field=models.CharField(blank=True, help_text='Orthostatic check -- red flag if drop >20 systolic', max_length=30),
        ),
        migrations.AddField(
            model_name='visitnote',
            name='geri_cognition',
            field=models.CharField(blank=True, help_text='e.g. Alert & oriented x3', max_length=100),
        ),
        migrations.AddField(
            model_name='visitnote',
            name='geri_dyspnea_borg_post',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='visitnote',
            name='geri_dyspnea_borg_pre',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='visitnote',
            name='geri_new_medications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visitnote',
            name='geri_orthostatic_dizziness_post',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitnote',
            name='geri_orthostatic_dizziness_pre',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitnote',
            name='geri_patient_report_post',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visitnote',
            name='geri_recovery_vitals',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='visitnote',
            name='geri_skin_check_pre',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visitnote',
            name='geri_spo2_post',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='visitnote',
            name='geri_spo2_pre',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='visitnote',
            name='geri_tug_post',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='visitnote',
            name='geri_tug_pre',
            field=models.CharField(blank=True, help_text='Timed Up and Go, seconds', max_length=20),
        ),
        migrations.AddField(
            model_name='visitnote',
            name='neuro_balance_sitting',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='visitnote',
            name='neuro_balance_standing',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='visitnote',
            name='neuro_bladder_bowel_status',
            field=models.TextField(blank=True, help_text='Esp. for SCI: bowel program, autonomic dysreflexia'),
        ),
        migrations.AddField(
            model_name='visitnote',
            name='neuro_fatigue_level',
            field=models.PositiveSmallIntegerField(blank=True, help_text='0-10', null=True),
        ),
        migrations.AddField(
            model_name='visitnote',
            name='neuro_fatigue_post',
            field=models.PositiveSmallIntegerField(blank=True, help_text='0-10', null=True),
        ),
        migrations.AddField(
            model_name='visitnote',
            name='neuro_gait_post',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visitnote',
            name='neuro_gait_pre',
            field=models.TextField(blank=True, help_text='e.g. 10-Meter Walk Test, deviations'),
        ),
        migrations.AddField(
            model_name='visitnote',
            name='neuro_motor_control',
            field=models.TextField(blank=True, help_text='e.g. synergy patterns, isolated movement'),
        ),
        migrations.AddField(
            model_name='visitnote',
            name='neuro_sensation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visitnote',
            name='neuro_skin_check_post',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visitnote',
            name='neuro_skin_check_pre',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visitnote',
            name='neuro_spasm_frequency',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visitnote',
            name='neuro_tone_post',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visitnote',
            name='neuro_tone_pre',
            field=models.TextField(blank=True, help_text='e.g. MAS scores by body part, clonus'),
        ),
        migrations.AddField(
            model_name='visitnote',
            name='treatment_provided',
            field=models.TextField(blank=True),
        ),
    ]
