# Generated by Django 5.2.14 on 2026-08-03 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0005_user_license_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pairing_token',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True, unique=True),
        ),
    ]
