# Generated by Django 5.2.14 on 2026-08-13 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0007_backfill_pairing_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('personal', 'Personal Account User'), ('clinic', 'Clinic User'), ('enterprise', 'Enterprise User'), ('rider', 'Rider')], default='personal', max_length=10),
        ),
    ]
