# Generated by Django 5.2.14 on 2026-08-18 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0008_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='license_verified',
            field=models.BooleanField(default=False),
        ),
    ]
