# Generated by Django 5.2.14 on 2026-10-04 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal_account', '0015_addpatient_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialTestReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('low_back', 'Low Back Pain'), ('cervical', 'Cervical'), ('knee', 'Knee')], max_length=20)),
                ('name', models.CharField(help_text='e.g. "Straight Leg Raise (SLR) Test"', max_length=150)),
                ('purpose', models.CharField(help_text='What it screens for, e.g. "Lumbar nerve root irritation / disc herniation"', max_length=255)),
                ('procedure', models.TextField(blank=True, help_text='Brief how-to')),
                ('positive_sign', models.TextField(blank=True, help_text='What a positive result looks like')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order within the region')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['region', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RegionalAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.CharField(choices=[('low_back', 'Low Back Pain'), ('cervical', 'Cervical'), ('knee', 'Knee')], max_length=20)),
                ('chief_complaint', models.TextField(blank=True, help_text='Why this assessment -- presenting complaint')),
                ('observation', models.TextField(blank=True, help_text='Posture, gait, swelling, deformity')),
                ('range_of_motion', models.TextField(blank=True)),
                ('palpation', models.TextField(blank=True)),
                ('special_tests', models.TextField(blank=True, help_text='Which tests performed and findings -- see reference list for this region')),
                ('neurovascular_screen', models.TextField(blank=True, help_text='Sensation, reflexes, pulses, red flags')),
                ('clinical_impression', models.TextField(blank=True, help_text="Physio's summary / working diagnosis from this assessment")),
                ('plan', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regional_assessments_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regional_assessments', to='personal_account.addpatient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
