# Generated by Django 5.2.14 on 2026-10-05 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionalassessment',
            name='region',
            field=models.CharField(choices=[('low_back', 'Low Back Pain'), ('cervical', 'Cervical'), ('knee', 'Knee'), ('parkinsons', "Parkinson's Disease")], max_length=20),
        ),
        migrations.AlterField(
            model_name='specialtestreference',
            name='region',
            field=models.CharField(choices=[('low_back', 'Low Back Pain'), ('cervical', 'Cervical'), ('knee', 'Knee'), ('parkinsons', "Parkinson's Disease")], max_length=20),
        ),
    ]
