# Generated by Django 5.2.14 on 2026-10-05 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_app', '0002_alter_regionalassessment_region_and_more'),
        ('personal_account', '0020_patientassessmententry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientScaleAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scale', models.CharField(choices=[('hoehn_yahr', 'Hoehn and Yahr Staging Scale'), ('tug', 'Timed Up and Go (TUG)'), ('berg_balance', 'Berg Balance Scale (BBS)'), ('lpas', "Lindop Parkinson's Physiotherapy Assessment Scale (LPAS)"), ('nfogq', 'New Freezing of Gait Questionnaire (NFOG-Q)')], max_length=20)),
                ('items', models.JSONField(default=dict, help_text='Raw per-item scores/values -- shape depends on scale, see scales.py')),
                ('total_score', models.CharField(blank=True, help_text='The headline number/stage for this administration', max_length=20)),
                ('interpretation', models.CharField(blank=True, help_text='Auto-computed from total_score at save time', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scale_assessments_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scale_assessments', to='personal_account.addpatient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
